export const BUDNLES = {
  bundles: [
    {
      id: 10,
      bgImage: "...",
      timeLeftMs: 3600000,
      maxAvailable: 10,
      available: 5,
      price: {
        amount: 99,
        currencySymbol: "$",
      },
      products: [
        {
          id: 0,
          name: "Gems",
          productImage: "asset-gems.png",
          amount: "6,000",
          productTextColor: "teal",
        },
        {
          id: 1,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "30M",
          productTextColor: "gold",
        },
        {
          id: 2,
          name: "Energy",
          productImage: "asset-energy.png",
          amount: "20",
          productTextColor: "purple",
        },
      ],
    },
    {
      id: 11,
      bgImage: "...",
      timeLeftMs: 7200000,
      maxAvailable: 20,
      available: 15,
      price: {
        amount: 149,
        currencySymbol: "$",
      },
      products: [
        {
          id: 0,
          name: "Energy",
          productImage: "asset-energy.png",
          amount: "12,000",
          productTextColor: "blue",
        },
        {
          id: 1,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "60M",
          productTextColor: "gold",
        },
        {
          id: 2,
          name: "Gems",
          productImage: "asset-gems.png",
          amount: "40",
          productTextColor: "pink",
        },
      ],
    },
    {
      id: 12,
      bgImage: "...",
      timeLeftMs: 10800000,
      maxAvailable: 5,
      available: 2,
      price: {
        amount: 199,
        currencySymbol: "$",
      },
      products: [
        {
          id: 0,
          name: "Gems",
          productImage: "asset-gems.png",
          amount: "18,000",
          productTextColor: "green",
        },
        {
          id: 1,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 2,
          name: "Energy",
          productImage: "asset-energy.png",
          amount: "60",
          productTextColor: "red",
        },
      ],
    },
    {
      id: 13,
      bgImage: "...",
      timeLeftMs: 1089809843,
      maxAvailable: 50,
      available: 12,
      price: {
        amount: 599,
        currencySymbol: "$",
      },
      products: [
        {
          id: 0,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 1,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 2,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 3,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },

        {
          id: 4,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 5,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 6,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 7,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 8,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 9,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 10,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 11,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 12,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 13,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 14,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 15,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 16,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 17,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 18,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 19,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 20,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 21,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 22,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 23,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 24,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 25,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 26,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 27,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 28,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 29,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
        {
          id: 30,
          name: "Coins",
          productImage: "asset-coins.png",
          amount: "100M",
          productTextColor: "gold",
        },
      ],
    },
  ],
};
